/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.CostumeStatisticDAO;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.NumberFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.github.lgooddatepicker.components.DatePicker;
import model.CostumeStatistic;
import model.User;

/**
 *
 * @author Nghaiz
 */
public class CostumeStatisticFrm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CostumeStatisticFrm.class.getName());
    private final User user;
    private final NumberFormat currencyFormat = NumberFormat.getCurrencyInstance(new Locale("vi", "VN"));
    private final DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    private List<CostumeStatistic> listCostume = new ArrayList<>();
    private java.util.Date currentStartDate;
    private java.util.Date currentEndDate;

    /**
     * Creates new form CostumeStatisticFrm
     */
    public CostumeStatisticFrm(User user) {
        initComponents();
        this.user = user;
        this.setLocationRelativeTo(null);
        configureDatePickers();
        lblErrorStartDate.setForeground(Color.RED);
        lblErrorEndDate.setForeground(Color.RED);
        clearErrors();
        configureCostumeTableClick();
    }

    public CostumeStatisticFrm(User user, CostumeStatisticSearchState searchState) {
        this(user);
        restoreSearchState(searchState);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCostumeStat = new javax.swing.JTable();
        txtStartDate = new com.github.lgooddatepicker.components.DatePicker();
        txtEndDate = new com.github.lgooddatepicker.components.DatePicker();
        lblErrorStartDate = new javax.swing.JLabel();
        lblErrorEndDate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thống kê trang phục được mượn nhiều");

        jLabel1.setText("Ngày bắt đầu:");

        jLabel2.setText("Ngày kết thúc:");

        btnSearch.setText("Thống kê");
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Thống kê"));

        tblCostumeStat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã trang phục", "Tên trang phục", "Kiểu", "Chủng loại", "Tổng số lượt mượn", "Tổng tiền thu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCostumeStat.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblCostumeStat);
        if (tblCostumeStat.getColumnModel().getColumnCount() > 0) {
            tblCostumeStat.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        lblErrorStartDate.setText(" ");

        lblErrorEndDate.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 20, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblErrorStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblErrorEndDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEndDate, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(btnSearch)
                    .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblErrorStartDate)
                    .addComponent(lblErrorEndDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        clearErrors();

        LocalDate startLocalDate = txtStartDate.getDate();
        LocalDate endLocalDate = txtEndDate.getDate();
        if (!isValidDateRange(startLocalDate, endLocalDate)) {
            return;
        }

        java.util.Date startDate = java.util.Date.from(startLocalDate.atStartOfDay(ZoneId.systemDefault()).toInstant());
        java.util.Date endDate = java.util.Date.from(endLocalDate.atStartOfDay(ZoneId.systemDefault()).toInstant());

        CostumeStatisticDAO costumeStatisticDAO = new CostumeStatisticDAO();
        currentStartDate = startDate;
        currentEndDate = endDate;
        listCostume = costumeStatisticDAO.getCostumeStatistic(startDate, endDate);
        showCostumeStatistics(listCostume);
        updateStatisticTitle(startLocalDate, endLocalDate);

        if (listCostume.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không có dữ liệu thống kê trong khoảng thời gian đã chọn.");
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void clearErrors() {
        lblErrorStartDate.setText(" ");
        lblErrorEndDate.setText(" ");
    }

    private boolean isValidDateRange(LocalDate startDate, LocalDate endDate) {
        boolean valid = true;
        String startDateText = txtStartDate.getText().trim();
        String endDateText = txtEndDate.getText().trim();

        if (startDateText.isEmpty()) {
            lblErrorStartDate.setText("Vui lòng chọn ngày bắt đầu");
            valid = false;
        } else if (startDate == null || !txtStartDate.isTextFieldValid()) {
            lblErrorStartDate.setText("Ngày bắt đầu phải có dạng dd/MM/yyyy");
            valid = false;
        }
        if (endDateText.isEmpty()) {
            lblErrorEndDate.setText("Vui lòng chọn ngày kết thúc");
            valid = false;
        } else if (endDate == null || !txtEndDate.isTextFieldValid()) {
            lblErrorEndDate.setText("Ngày kết thúc phải có dạng dd/MM/yyyy");
            valid = false;
        }
        if (valid && startDate.isAfter(endDate)) {
            lblErrorStartDate.setText("Ngày bắt đầu không được sau ngày kết thúc");
            lblErrorEndDate.setText("Ngày kết thúc không được trước ngày bắt đầu");
            valid = false;
        }
        return valid;
    }

    private void showCostumeStatistics(List<CostumeStatistic> listCostume) {
        DefaultTableModel tableModel = (DefaultTableModel) tblCostumeStat.getModel();
        tableModel.setRowCount(0);
        for (int i = 0; i < listCostume.size(); i++) {
            CostumeStatistic cs = listCostume.get(i);
            tableModel.addRow(new Object[]{
                    i + 1,
                    cs.getId(),
                    cs.getName(),
                    cs.getType(),
                    cs.getCategory(),
                    cs.getTotalRentalTimes(),
                    currencyFormat.format(cs.getTotalRevenue())
            });
        }
    }

    private void configureDatePickers() {
        configureDatePicker(txtStartDate);
        configureDatePicker(txtEndDate);
    }

    private void configureDatePicker(DatePicker datePicker) {
        ArrayList<DateTimeFormatter> parsingFormats = new ArrayList<>();
        parsingFormats.add(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        parsingFormats.add(DateTimeFormatter.ofPattern("d/M/yyyy"));

        datePicker.getSettings().setFormatForDatesCommonEra("dd/MM/yyyy");
        datePicker.getSettings().setFormatsForParsing(parsingFormats);
    }

    private void updateStatisticTitle(LocalDate startDate, LocalDate endDate) {
        String title = "Thống kê từ " + startDate.format(dateFormatter) + " đến " + endDate.format(dateFormatter);
        jScrollPane1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createTitledBorder(""), title));
        jScrollPane1.repaint();
    }

    private void configureCostumeTableClick() {
        tblCostumeStat.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                if (evt.getClickCount() == 1) {
                    openSelectedCostumeStatistic();
                }
            }
        });
    }

    private void openSelectedCostumeStatistic() {
        int selectedRow = tblCostumeStat.getSelectedRow();
        if (selectedRow < 0 || currentStartDate == null || currentEndDate == null) {
            return;
        }

        int modelRow = tblCostumeStat.convertRowIndexToModel(selectedRow);
        if (modelRow < 0 || modelRow >= listCostume.size()) {
            return;
        }

        RentalBillStatisticFrm rentalBillStatisticFrm = new RentalBillStatisticFrm(
                user,
                listCostume.get(modelRow),
                currentStartDate,
                currentEndDate,
                createSearchState()
        );
        rentalBillStatisticFrm.setVisible(true);
        this.dispose();
    }

    private void restoreSearchState(CostumeStatisticSearchState searchState) {
        if (searchState == null || searchState.getStartDate() == null || searchState.getEndDate() == null) {
            return;
        }

        currentStartDate = searchState.getStartDate();
        currentEndDate = searchState.getEndDate();
        LocalDate startLocalDate = currentStartDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate endLocalDate = currentEndDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

        txtStartDate.setDate(startLocalDate);
        txtEndDate.setDate(endLocalDate);
        listCostume = new ArrayList<>(searchState.getCostumeStatistics());
        showCostumeStatistics(listCostume);
        updateStatisticTitle(startLocalDate, endLocalDate);
    }

    private CostumeStatisticSearchState createSearchState() {
        return new CostumeStatisticSearchState(currentStartDate, currentEndDate, listCostume);
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new CostumeStatisticFrm().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblErrorEndDate;
    private javax.swing.JLabel lblErrorStartDate;
    private javax.swing.JTable tblCostumeStat;
    private com.github.lgooddatepicker.components.DatePicker txtEndDate;
    private com.github.lgooddatepicker.components.DatePicker txtStartDate;
    // End of variables declaration//GEN-END:variables
}
