/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.RentalBillDAO;
import model.CostumeStatistic;
import model.RentalBill;
import model.User;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.NumberFormat;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nghaiz
 */
public class RentalBillStatisticFrm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RentalBillStatisticFrm.class.getName());
    private User user;
    private CostumeStatistic costumeStatistic;
    private Date startDate;
    private Date endDate;
    private CostumeStatisticSearchState costumeStatisticSearchState;
    private List<RentalBill> rentalBills = new ArrayList<>();
    private final NumberFormat currencyFormat = NumberFormat.getCurrencyInstance(new Locale("vi", "VN"));
    private final DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

    /**
     * Creates new form RentalBillStatisticFrm
     */
    public RentalBillStatisticFrm() {
        initComponents();
        this.setLocationRelativeTo(null);
        configureRentalBillTableClick();
        jButton1.addActionListener(this::btnBackActionPerformed);
    }

    public RentalBillStatisticFrm(User user, CostumeStatistic costumeStatistic, Date startDate, Date endDate) {
        this(user, costumeStatistic, startDate, endDate, null);
    }

    public RentalBillStatisticFrm(
            User user,
            CostumeStatistic costumeStatistic,
            Date startDate,
            Date endDate,
            CostumeStatisticSearchState costumeStatisticSearchState
    ) {
        this();
        this.user = user;
        this.costumeStatistic = costumeStatistic;
        this.startDate = startDate;
        this.endDate = endDate;
        this.costumeStatisticSearchState = costumeStatisticSearchState;
        loadRentalBills();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thống kê danh sách phiếu mượn");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Thống kê"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã phiếu mượn", "Tên khách hàng", "Số lượng", "Ngày tạo phiếu", "Lợi nhuận"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        jLabel1.setText("Trang phục:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText(" ");

        jLabel3.setText("Tổng lợi nhuận:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText(" ");

        jButton1.setText("Quay lại");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadRentalBills() {
        if (costumeStatistic == null || startDate == null || endDate == null) {
            return;
        }

        jLabel4.setText(costumeStatistic.getName());
        jLabel2.setText(currencyFormat.format(costumeStatistic.getTotalRevenue()));
        updateStatisticTitle();

        RentalBillDAO rentalBillDAO = new RentalBillDAO();
        rentalBills = rentalBillDAO.getBillDetailByCostume(costumeStatistic.getId(), startDate, endDate);
        showRentalBills();

        if (rentalBills.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không có phiếu mượn trang phục này trong khoảng thời gian đã chọn.");
        }
    }

    private void showRentalBills() {
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        tableModel.setRowCount(0);
        for (int i = 0; i < rentalBills.size(); i++) {
            RentalBill rentalBill = rentalBills.get(i);
            tableModel.addRow(new Object[]{
                    i + 1,
                    rentalBill.getId(),
                    rentalBill.getClient() == null ? "" : rentalBill.getClient().getFullname(),
                    rentalBill.getTotalQuantity(),
                    rentalBill.getCreatedAt() == null ? "" : rentalBill.getCreatedAt().format(dateFormatter),
                    currencyFormat.format(rentalBill.getTotalRevenue())
            });
        }
    }

    private void configureRentalBillTableClick() {
        jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                if (evt.getClickCount() == 1) {
                    openSelectedRentalBill();
                }
            }
        });
    }

    private void openSelectedRentalBill() {
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow < 0 || startDate == null || endDate == null) {
            return;
        }

        int modelRow = jTable1.convertRowIndexToModel(selectedRow);
        if (modelRow < 0 || modelRow >= rentalBills.size()) {
            return;
        }

        RentalBillDetailFrm rentalBillDetailFrm = new RentalBillDetailFrm(
                user,
                rentalBills.get(modelRow).getId(),
                startDate,
                endDate,
                costumeStatistic,
                costumeStatisticSearchState
        );
        rentalBillDetailFrm.setVisible(true);
        this.dispose();
    }

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {
        if (user != null) {
            CostumeStatisticFrm costumeStatisticFrm = costumeStatisticSearchState == null
                    ? new CostumeStatisticFrm(user)
                    : new CostumeStatisticFrm(user, costumeStatisticSearchState);
            costumeStatisticFrm.setVisible(true);
        }
        this.dispose();
    }

    private void updateStatisticTitle() {
        String title = "Danh sách phiếu mượn từ "
                + startDate.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate().format(dateFormatter)
                + " đến "
                + endDate.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate().format(dateFormatter);
        jScrollPane1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createTitledBorder(""), title));
        jScrollPane1.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RentalBillStatisticFrm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
