/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.Collateral;
import model.Costume;
import model.CostumeStatistic;
import model.RentalBill;
import model.RentalCollateral;
import model.RentedCostume;
import model.ReturnedCostume;
import model.User;

import java.text.NumberFormat;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nghaiz
 */
public class RentalBillDetailFrm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RentalBillDetailFrm.class.getName());
    private User user;
    private Date startDate;
    private Date endDate;
    private CostumeStatistic costumeStatistic;
    private CostumeStatisticSearchState costumeStatisticSearchState;
    private RentalBill rentalBill;
    private List<ReturnedCostume> returnedCostumes = new ArrayList<>();
    private final NumberFormat currencyFormat = NumberFormat.getCurrencyInstance(new Locale("vi", "VN"));
    private final DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

    /**
     * Creates new form RentalBillDetailFrm
     */
    public RentalBillDetailFrm() {
        initComponents();
        this.setLocationRelativeTo(null);
        jButton1.addActionListener(this::btnBackActionPerformed);
    }

    public RentalBillDetailFrm(
            User user,
            RentalBill rentalBill,
            List<ReturnedCostume> returnedCostumes,
            Date startDate,
            Date endDate,
            CostumeStatistic costumeStatistic,
            CostumeStatisticSearchState costumeStatisticSearchState
    ) {
        this();
        this.user = user;
        this.rentalBill = rentalBill;
        this.returnedCostumes = returnedCostumes == null ? new ArrayList<>() : returnedCostumes;
        this.startDate = startDate;
        this.endDate = endDate;
        this.costumeStatistic = costumeStatistic;
        this.costumeStatisticSearchState = costumeStatisticSearchState;
        showRentalBillDetail();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thông tin chi tiết phiếu mượn");

        jPanel1.setLayout(new java.awt.GridLayout(4, 2));

        jLabel1.setText("Mã hóa đơn:");
        jPanel1.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText(" ");
        jPanel1.add(jLabel2);

        jLabel3.setText("Mã khách hàng:");
        jPanel1.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText(" ");
        jPanel1.add(jLabel4);

        jLabel5.setText("Tên khách hàng:");
        jPanel1.add(jLabel5);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText(" ");
        jPanel1.add(jLabel6);

        jLabel7.setText("Ngày tạo phiếu:");
        jPanel1.add(jLabel7);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText(" ");
        jPanel1.add(jLabel8);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Các trang phục khách đã mượn"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã trang phục", "Tên trang phục", "Kiểu trang phục", "Chủng loại trang phục", "Số lượng", "Giá mượn", "Ngày mượn", "Ngày hẹn trả", "Ngày khách trả", "Tổng số tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMaxWidth(80);
        }

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Các món đồ khách đã đặt cọc"));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Loại tài sản", "Giá trị"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setMaxWidth(80);
        }

        jPanel2.setLayout(new java.awt.GridLayout(4, 2));

        jLabel9.setText("Giảm giá:");
        jPanel2.add(jLabel9);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText(" ");
        jPanel2.add(jLabel10);

        jLabel11.setText("Ghi chú:");
        jPanel2.add(jLabel11);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText(" ");
        jPanel2.add(jLabel12);

        jLabel13.setText("Tổng số trang phục:");
        jPanel2.add(jLabel13);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText(" ");
        jPanel2.add(jLabel14);

        jLabel15.setText("Tổng số tiền thu được:");
        jPanel2.add(jLabel15);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText(" ");
        jPanel2.add(jLabel16);

        jButton1.setText("Quay lại");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showRentalBillDetail() {
        if (rentalBill == null) {
            return;
        }

        showRentalBillInfo();
        showReturnedCostumes();
        showRentalCollaterals();
        showTotals();
    }

    private void showRentalBillInfo() {
        jLabel2.setText(String.valueOf(rentalBill.getId()));
        jLabel4.setText(rentalBill.getClient() == null ? "" : String.valueOf(rentalBill.getClient().getId()));
        jLabel6.setText(rentalBill.getClient() == null ? "" : rentalBill.getClient().getFullname());
        jLabel8.setText(rentalBill.getCreatedAt() == null ? "" : rentalBill.getCreatedAt().format(dateFormatter));
        jLabel10.setText(currencyFormat.format(rentalBill.getSaleoff()));
        jLabel12.setText(rentalBill.getNote() == null ? "" : rentalBill.getNote());
    }

    private void showReturnedCostumes() {
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        tableModel.setRowCount(0);

        for (ReturnedCostume returnedCostume : returnedCostumes) {
            RentedCostume rentedCostume = returnedCostume.getRentedCostume();
            Costume costume = rentedCostume == null ? null : rentedCostume.getCostume();
            tableModel.addRow(new Object[]{
                    costume == null ? "" : costume.getId(),
                    costume == null ? "" : costume.getName(),
                    costume == null ? "" : costume.getType(),
                    costume == null ? "" : costume.getCategory(),
                    returnedCostume.getReturnedQuantity(),
                    rentedCostume == null ? "" : currencyFormat.format(rentedCostume.getRentalPrice()),
                    rentedCostume == null || rentedCostume.getRentedAt() == null
                            ? ""
                            : rentedCostume.getRentedAt().format(dateFormatter),
                    rentedCostume == null || rentedCostume.getDateToReturn() == null
                            ? ""
                            : rentedCostume.getDateToReturn().format(dateFormatter),
                    returnedCostume.getReturnedAt() == null
                            ? "Chưa trả"
                            : returnedCostume.getReturnedAt().format(dateFormatter),
                    currencyFormat.format(returnedCostume.getTotalAmount())
            });
        }
    }

    private void showRentalCollaterals() {
        DefaultTableModel tableModel = (DefaultTableModel) jTable2.getModel();
        tableModel.setRowCount(0);

        List<RentalCollateral> rentalCollaterals = rentalBill.getListRentalCollateral();
        for (int i = 0; i < rentalCollaterals.size(); i++) {
            RentalCollateral rentalCollateral = rentalCollaterals.get(i);
            Collateral collateral = rentalCollateral.getCollateral();
            tableModel.addRow(new Object[]{
                    i + 1,
                    collateral == null ? "" : collateral.getName(),
                    currencyFormat.format(rentalCollateral.getValue())
            });
        }
    }

    private void showTotals() {
        int totalQuantity = 0;
        float totalAmount = 0;
        for (ReturnedCostume returnedCostume : returnedCostumes) {
            totalQuantity += returnedCostume.getReturnedQuantity();
            totalAmount += returnedCostume.getTotalAmount();
        }
        jLabel14.setText(String.valueOf(totalQuantity));
        jLabel16.setText(currencyFormat.format(totalAmount));
    }

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {
        if (user != null && costumeStatistic != null && startDate != null && endDate != null) {
            RentalBillStatisticFrm rentalBillStatisticFrm = new RentalBillStatisticFrm(
                    user,
                    costumeStatistic,
                    startDate,
                    endDate,
                    costumeStatisticSearchState
            );
            rentalBillStatisticFrm.setVisible(true);
        }
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RentalBillDetailFrm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
